[package]
name = "rake"
version = "0.1.0"
authors = ["azarashi2931 <46126763+azarashi2931@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
